### ISSUE TITLE
py3.13: not building with pip

### ISSUE THREAD

**Issue by sanjayankur31** [fbergmann/libSEDML#175]
Hi there,

py3.13 has now been released. While testing pyNeuroML in py3.13, we noticed that libsedml isn't being built correctly with pip:

```
Collecting python-libsedml (from pyNeuroML==1.3.13)
  Downloading python-libsedml-2.0.31.tar.gz (6.7 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Using libSedML from: /tmp/pip-install-76d2ejc1/python-libsedml_fd8ebd5a55f14c228c1c4e28ca558e27
      Using VERSION.txt: /tmp/pip-install-76d2ejc1/python-libsedml_fd8ebd5a55f14c228c1c4e28ca558e27/VERSION.txt
      ['setup.py', 'LICENSE.txt', 'PKG-INFO', 'README.md', 'setup.cfg', 'python_libsedml.egg-info']
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-q1xujmjj/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-q1xujmjj/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-q1xujmjj/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 516, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-q1xujmjj/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 117, in <module>
      ValueError: Invalid libSedML Source directory, no VERSION.txt file
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

(Not entirely sure what the issue is currently)

**Comment by fbergmann** [comment]
Thanks for letting me know. I've updated the python-libsedml package to include 3.13 binaries ... i'll do the same for libsbml tomorrow.

**Comment by fbergmann** [comment]
closing this since 3.13 binaries have been out for a quite some time.
