### ISSUE TITLE
pip package not installing on py3.6 on ubuntu

### ISSUE THREAD

**Issue by matthiaskoenig** [fbergmann/libSEDML#50]
Hi all,
I just tried to install the python package on Ubuntu 16.04 via pip.
The installation is working, but when trying to import the package I get the following ImportError:

```
(sbmlutils) mkoenig@mkxps:~/git/sbmlutils$ pip install python-libsedml --force-reinstall --no-cache-dir
Collecting python-libsedml
  Downloading python-libsedml-0.4.1.tar.gz (2.9MB)
    100% |████████████████████████████████| 2.9MB 12.3MB/s 
Installing collected packages: python-libsedml
  Running setup.py install for python-libsedml ... done
Successfully installed python-libsedml-0.4.1
(sbmlutils) mkoenig@mkxps:~/git/sbmlutils$ python
Python 3.6.1+ (default, Jun  8 2017, 12:24:27) 
[GCC 5.4.1 20170519] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsedml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/libsedml/libsedml.py", line 28, in <module>
    _libsedml = swig_import_helper()
  File "/usr/local/lib/python2.7/site-packages/libsedml/libsedml.py", line 24, in swig_import_helper
    _mod = imp.load_module('_libsedml', fp, pathname, description)
  File "/home/mkoenig/envs/sbmlutils/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/mkoenig/envs/sbmlutils/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dynamic module does not define module export function (PyInit__libsedml)
```

Matthias

**Comment by fbergmann** [comment]
I'm a bit confused as to why you python 3.6 would be importing a python 2.7 module ... I will have a look as to what is happening here ...

**Comment by matthiaskoenig** [comment]
This is installed in a virtualenv which uses python 3.6. My system library is python is 2.7 so probably somehow this mixed up the detection of the right python version.

**Comment by fbergmann** [comment]
Can you give me precise instructions so that i can reproduce the issue? For me pip uses python 2.7 and all seems to work fine. I need a failing command line for testing. 

```
fbergmann@ubuntu:~$ pip install python-libsedml
Collecting python-libsedml
  Downloading python-libsedml-0.4.1.tar.gz (2.9MB)
    100% |████████████████████████████████| 2.9MB 605kB/s 
Building wheels for collected packages: python-libsedml
  Running setup.py bdist_wheel for python-libsedml ... done
  Stored in directory: /home/fbergmann/.cache/pip/wheels/0a/2b/f9/3852ad514647b60070742a6d2607041c0cb9fb560e631bb924
Successfully built python-libsedml
Installing collected packages: python-libsedml
Successfully installed python-libsedml-0.4.1
fbergmann@ubuntu:~$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsedml
>>> print libsedml.getLibSEDMLDottedVersion()
0.4.1
>>> 

```

thanks

**Comment by matthiaskoenig** [comment]
Hi Frank, 
I figured it out while trying to log everything :)

The problem was that the libsedml of my system was in the PYTHONPATH which overwrote the libsedml in the virtualenv. Subsequently the `import libsedml` tried to import the py27 version in py36.

Thanks for your help.
M
